FROM ubuntu:questing-20251007
LABEL maintainer="Nigel Poulton nigelpoulton@hotmail.com @nigelpoulton"
# Update packages and install curl 
RUN apt-get update && apt-get install -y \
  curl \
  dnsutils